import { sampleDashboardData } from "./sampleData";
import type { DashboardData, SignalRow } from "./types";

const API_BASE_URL = import.meta.env.VITE_API_BASE_URL ?? "http://localhost:8000";

function lastValue(values: string[]): string | undefined {
  return values.length ? values[values.length - 1] : undefined;
}

type HealthResponse = {
  status?: string;
  service?: string;
};

type SignalsResponse = {
  signals?: SignalRow[];
};

async function fetchJson<T>(path: string): Promise<T> {
  const response = await fetch(`${API_BASE_URL}${path}`);
  if (!response.ok) {
    throw new Error(`${path} returned ${response.status}`);
  }
  return (await response.json()) as T;
}

export async function loadDashboardData(): Promise<DashboardData> {
  try {
    const [health, latestSignals] = await Promise.all([
      fetchJson<HealthResponse>("/health"),
      fetchJson<SignalsResponse>("/signals/latest")
    ]);
    const signals = latestSignals.signals ?? [];
    if (!signals.length) {
      throw new Error("No live signals returned");
    }
    const latestRunTime =
      lastValue(
        signals
        .map((row) => row.generated_at)
        .filter(Boolean)
        .sort() as string[]
      ) ?? lastValue(signals.map((row) => row.date).sort()) ?? "unknown";

    return {
      source: "live API",
      databaseStatus: health.status === "ok" ? "online" : "unavailable",
      latestRunTime,
      aiSummary:
        "Live signal data loaded from the FastAPI service. AI market summaries are generated by the backend report pipeline when OPENAI_API_KEY is configured; run the pipeline with --no-ai to disable AI commentary.",
      signals
    };
  } catch {
    return sampleDashboardData;
  }
}
